services:
  caddy-proxy:
    image: caddy:latest
    cap_add:
      - NET_ADMIN
    container_name: caddy_main_proxy
    restart: unless-stopped
#    environment:
#      CADDY_INGRESS_NETWORKS: web_network
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: udp
        mode: host
    volumes:
      - ./config/Caddyfile:/etc/caddy/Caddyfile
      - caddy_proxy_data:/data
      - caddy_proxy_config:/config
    networks:
      - web_network

networks:
  web_network:
    driver: bridge
    external: true

volumes:
  caddy_proxy_data:
  caddy_proxy_config:
