services:
  caddy-proxy:
    image: caddy:latest
    container_name: caddy_main_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./config/Caddyfile:/etc/caddy/Caddyfile
      - caddy_proxy_data:/data
      - caddy_proxy_config:/config
    networks:
      - web_network

networks:
  web_network:
    driver: bridge
    external: true

volumes:
  caddy_proxy_data:
  caddy_proxy_config:
